version: '2'
services:
  appointment-hazelcast-management-center:
    image: hazelcast/management-center:3.12.8
    volumes:
      - /data/hazelcast:/data
      - /etc/localtime:/etc/localtime
    ports:
      - 8080:8080
