version: '2'
services:
  appointment-mysql:
    image: mysql:8.0.19
    volumes:
      - /data/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=app@123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=appointment
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
